name: compass
channels:
        - damianavila82
        - defaults
dependencies:
        - python=3.6
        - jupyter
        - matplotlib
        - json
        - pandas
        - ipywidgets
        - rise
        - pip:
            - tqdm
